name: Deploy to Azure Web App

on:
  push:
    branches:
      - main
      - master

env:
  AZURE_WEBAPP_NAME: ptslove    # Web App name in Azure
  AZURE_WEBAPP_PACKAGE_PATH: './build'  # Caminho para a pasta de build
  NODE_VERSION: '18.x'               # Versão do Node.js

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Clean install dependencies
      run: |
        npm ci

    - name: Build
      run: |
        npm run build
        
    - name: Prepare for deployment
      run: |
        rm -rf node_modules
        npm ci --only=production
        mkdir -p build
        cp -r .next build/
        cp -r node_modules build/
        cp package.json build/
        cp next.config.js build/
        cp server.js build/

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        type: 'zip'
        clean: true
